In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline
import seaborn as sns
from matplotlib import rcParams
import plotly.express as px
import plotly.graph_objects as go
from matplotlib import font_manager as fm


import warnings
warnings.filterwarnings(action='ignore')
import os

In [2]:
df =pd.read_csv(r"C:\Users\kelvin\OneDrive\Desktop\DataScience\credit_risk_dataset_training.csv")
print(df.shape)
df.head()

(22850, 12)


person_age  person_income person_home_ownership  person_emp_length   
0          22          59000                  RENT              123.0  \
1          21           9600                   OWN                5.0   
2          23          65500                  RENT                4.0   
3          21           9900                   OWN                2.0   
4          26          77100                  RENT                8.0   

  loan_intent loan_grade  loan_amnt  loan_int_rate  loan_status   
0    PERSONAL          D      35000          16.02            1  \
1   EDUCATION          B       1000          11.14            0   
2     MEDICAL          C      35000          15.23            1   
3     VENTURE          A       2500           7.14            1   
4   EDUCATION          B      35000          12.42            1   

   loan_percent_income cb_person_default_on_file  cb_person_cred_hist_length  
0                 0.59                         Y                           3  
1                 0.10                         N                           2  
2                 0.53                         N                           2  
3                 0.25                         N                           2  
4                 0.45                         N                           3

In [3]:
df.columns=='float64'

array([False, False, False, False, False, False, False, False, False,
       False, False, False])

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 22850 entries, 0 to 22849
Data columns (total 12 columns):
 #   Column                      Non-Null Count  Dtype  
---  ------                      --------------  -----  
 0   person_age                  22850 non-null  int64  
 1   person_income               22850 non-null  int64  
 2   person_home_ownership       22850 non-null  object 
 3   person_emp_length           22237 non-null  float64
 4   loan_intent                 22850 non-null  object 
 5   loan_grade                  22850 non-null  object 
 6   loan_amnt                   22850 non-null  int64  
 7   loan_int_rate               20703 non-null  float64
 8   loan_status                 22850 non-null  int64  
 9   loan_percent_income         22850 non-null  float64
 10  cb_person_default_on_file   22850 non-null  object 
 11  cb_person_cred_hist_length  22850 non-null  int64  
dtypes: float64(3), int64(5), object(4)
memory usage: 2.1+ MB


In [5]:
df.dropna(inplace=True)

In [6]:
df.isna().sum()

person_age                    0
person_income                 0
person_home_ownership         0
person_emp_length             0
loan_intent                   0
loan_grade                    0
loan_amnt                     0
loan_int_rate                 0
loan_status                   0
loan_percent_income           0
cb_person_default_on_file     0
cb_person_cred_hist_length    0
dtype: int64

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 20136 entries, 0 to 22849
Data columns (total 12 columns):
 #   Column                      Non-Null Count  Dtype  
---  ------                      --------------  -----  
 0   person_age                  20136 non-null  int64  
 1   person_income               20136 non-null  int64  
 2   person_home_ownership       20136 non-null  object 
 3   person_emp_length           20136 non-null  float64
 4   loan_intent                 20136 non-null  object 
 5   loan_grade                  20136 non-null  object 
 6   loan_amnt                   20136 non-null  int64  
 7   loan_int_rate               20136 non-null  float64
 8   loan_status                 20136 non-null  int64  
 9   loan_percent_income         20136 non-null  float64
 10  cb_person_default_on_file   20136 non-null  object 
 11  cb_person_cred_hist_length  20136 non-null  int64  
dtypes: float64(3), int64(5), object(4)
memory usage: 2.0+ MB


In [8]:
from sklearn.preprocessing import OrdinalEncoder
y = df.iloc[:,8].values
X = df.iloc[:,[0,1,2,3,4,5,6,7,9,10,11]]
enc = OrdinalEncoder()
X_c = enc.fit_transform(X)
X_c

array([[2.000e+00, 1.555e+03, 3.000e+00, ..., 5.900e+01, 1.000e+00,
        1.000e+00],
       [1.000e+00, 1.200e+01, 2.000e+00, ..., 1.000e+01, 0.000e+00,
        0.000e+00],
       [3.000e+00, 1.775e+03, 3.000e+00, ..., 5.300e+01, 0.000e+00,
        0.000e+00],
       ...,
       [3.400e+01, 2.655e+03, 0.000e+00, ..., 1.500e+01, 0.000e+00,
        1.700e+01],
       [3.600e+01, 2.797e+03, 0.000e+00, ..., 1.000e+01, 0.000e+00,
        2.400e+01],
       [4.600e+01, 8.920e+02, 3.000e+00, ..., 1.500e+01, 0.000e+00,
        2.800e+01]])

In [9]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
X_s = scaler.fit_transform(X_c)

In [10]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense

In [11]:
model = Sequential()
model.add(Dense(32,activation = 'relu',input_dim=11))
model.add(Dense(16,activation = 'relu'))
model.add(Dense(1,activation = 'sigmoid'))

In [12]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(X_s,y,test_size=0.3,random_state=42)
print(X_train.shape)
print(X_test.shape)
print(y_train.shape)
print(y_test.shape)

(14095, 11)
(6041, 11)
(14095,)
(6041,)


In [13]:
model.compile(loss='binary_crossentropy',optimizer='rmsprop',metrics=['accuracy'])

In [21]:
model.fit(x=X_train,y=y_train,epochs=300,verbose=1)

Epoch 1/300
441/441 [==============================] - 2s 3ms/step - loss: 0.2209 - accuracy: 0.9246
Epoch 2/300
441/441 [==============================] - 2s 4ms/step - loss: 0.2195 - accuracy: 0.9254
Epoch 3/300
441/441 [==============================] - 2s 4ms/step - loss: 0.2197 - accuracy: 0.9249
Epoch 4/300
441/441 [==============================] - 2s 4ms/step - loss: 0.2201 - accuracy: 0.9247
Epoch 5/300
441/441 [==============================] - 2s 4ms/step - loss: 0.2198 - accuracy: 0.9240
Epoch 6/300
441/441 [==============================] - 2s 4ms/step - loss: 0.2192 - accuracy: 0.9257
Epoch 7/300
441/441 [==============================] - 2s 4ms/step - loss: 0.2189 - accuracy: 0.9257
Epoch 8/300
441/441 [==============================] - 1s 3ms/step - loss: 0.2195 - accuracy: 0.9249
Epoch 9/300
441/441 [==============================] - 2s 4ms/step - loss: 0.2195 - accuracy: 0.9249
Epoch 10/300
441/441 [==============================] - 2s 4ms/step - loss: 0.2181 - accura

441/441 [==============================] - 2s 4ms/step - loss: 0.2133 - accuracy: 0.9283
Epoch 160/300
441/441 [==============================] - 2s 5ms/step - loss: 0.2140 - accuracy: 0.9281
Epoch 161/300
441/441 [==============================] - 2s 4ms/step - loss: 0.2136 - accuracy: 0.9291
Epoch 162/300
441/441 [==============================] - 2s 4ms/step - loss: 0.2138 - accuracy: 0.9278
Epoch 163/300
441/441 [==============================] - 2s 4ms/step - loss: 0.2143 - accuracy: 0.9281
Epoch 164/300
441/441 [==============================] - 2s 3ms/step - loss: 0.2136 - accuracy: 0.9287
Epoch 165/300
441/441 [==============================] - 1s 3ms/step - loss: 0.2142 - accuracy: 0.9286
Epoch 166/300
441/441 [==============================] - 2s 4ms/step - loss: 0.2141 - accuracy: 0.9286
Epoch 167/300
441/441 [==============================] - 2s 4ms/step - loss: 0.2125 - accuracy: 0.9291
Epoch 168/300
441/441 [==============================] - 2s 4ms/step - loss: 0.2140 - a

441/441 [==============================] - 2s 3ms/step - loss: 0.2140 - accuracy: 0.9286
Epoch 239/300
441/441 [==============================] - 2s 4ms/step - loss: 0.2145 - accuracy: 0.9281
Epoch 240/300
441/441 [==============================] - 2s 4ms/step - loss: 0.2140 - accuracy: 0.9293
Epoch 241/300
441/441 [==============================] - 2s 4ms/step - loss: 0.2142 - accuracy: 0.9286
Epoch 242/300
441/441 [==============================] - 2s 4ms/step - loss: 0.2135 - accuracy: 0.9299
Epoch 243/300
441/441 [==============================] - 2s 4ms/step - loss: 0.2136 - accuracy: 0.9289
Epoch 244/300
441/441 [==============================] - 2s 4ms/step - loss: 0.2143 - accuracy: 0.9302
Epoch 245/300
441/441 [==============================] - 2s 4ms/step - loss: 0.2163 - accuracy: 0.9276
Epoch 246/300
441/441 [==============================] - 2s 3ms/step - loss: 0.2148 - accuracy: 0.9291
Epoch 247/300
441/441 [==============================] - 2s 4ms/step - loss: 0.2127 - a

In [22]:
test_loss,test_accuracy = model.evaluate(X_train,y_train)
print(test_loss,test_accuracy)

441/441 [==============================] - 1s 3ms/step - loss: 0.2154 - accuracy: 0.9281
0.21541033685207367 0.928130567073822


In [23]:
y_pred=model.predict(X_test)
y_pred

189/189 [==============================] - 0s 2ms/step


array([[0.9520861 ],
       [0.01081089],
       [0.07689979],
       ...,
       [0.09442089],
       [0.0284473 ],
       [0.03268944]], dtype=float32)

In [28]:
y_pre=np.where(y_pred>0.55,1,0)
y_pre

array([[1],
       [0],
       [0],
       ...,
       [0],
       [0],
       [0]])

In [29]:
from sklearn.metrics import confusion_matrix,accuracy_score,classification_report
confusion_matrix(y_test,y_pre)

array([[4598,  116],
       [ 409,  918]], dtype=int64)

In [30]:
accuracy_score(y_test,y_pre)

0.9130938586326767

In [31]:
print(classification_report(y_test,y_pre))

              precision    recall  f1-score   support

           0       0.92      0.98      0.95      4714
           1       0.89      0.69      0.78      1327

    accuracy                           0.91      6041
   macro avg       0.90      0.83      0.86      6041
weighted avg       0.91      0.91      0.91      6041

