In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
from sklearn.metrics import mean_squared_error as MSE
from sklearn import datasets

from sklearn.model_selection import cross_val_score,train_test_split,GridSearchCV
from sklearn.pipeline import Pipeline,make_pipeline

In [3]:
from sklearn.ensemble import GradientBoostingClassifier,GradientBoostingRegressor
from sklearn.ensemble import RandomForestClassifier

from sklearn.metrics import accuracy_score,f1_score,confusion_matrix,classification_report

In [4]:
bike = datasets.load_iris()
X, y = bike.data, bike.target

In [5]:
dataset = pd.read_csv(r'C:\Users\kelvin\Downloads\Social_Network_Ads.csv')
X_train,X_test,y_train,y_test = train_test_split(X, y, test_size = 0.3,random_state=42)
#misssing

In [6]:
train_X, test_X, train_y, test_y = train_test_split(X, y, test_size = 0.3,random_state=42)

In [7]:
gbr = GradientBoostingRegressor(n_estimators = 200, max_depth = 1, random_state = 42)

In [8]:
gbr.fit(train_X, train_y)

GradientBoostingRegressor(max_depth=1, n_estimators=200, random_state=42)

GradientBoostingRegressor(max_depth=1, n_estimators=200, random_state=42)

In [9]:
pred = gbr.predict(test_X)

In [10]:
test_rmse = MSE(test_y, pred) ** (1 / 2)

In [11]:
print('RMSE test set: {:.2f}'.format(test_rmse))

RMSE test set: 0.10
RMSE test set: 0.10


In [12]:
dataset = pd.read_csv(r'C:\Users\kelvin\Downloads\Social_Network_Ads.csv')
dataset.head()

User ID  Gender  Age  EstimatedSalary  Purchased
0  15624510    Male   19            19000          0
1  15810944    Male   35            20000          0
2  15668575  Female   26            43000          0
3  15603246  Female   27            57000          0
4  15804002    Male   19            76000          0

User ID  Gender  Age  EstimatedSalary  Purchased
0  15624510    Male   19            19000          0
1  15810944    Male   35            20000          0
2  15668575  Female   26            43000          0
3  15603246  Female   27            57000          0
4  15804002    Male   19            76000          0

In [13]:
X_train,X_test,y_train,y_test = train_test_split(X, y, test_size = 0.3,random_state=42)
X = dataset.iloc[:, [2, 3]].values
y = dataset.iloc[:, 4].values
print("X",X.shape)
print("y",y.shape)

from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

from sklearn.tree import DecisionTreeClassifier
classifier1 = DecisionTreeClassifier(criterion='entropy', random_state=42)
classifier1.fit(X_train, y_train)

y_pred1 = classifier1.predict(X_test)

print("Accuracy:",accuracy_score(y_test, y_pred1))

X (400, 2)
y (400,)
Accuracy: 0.9555555555555556
X (400, 2)
y (400,)
Accuracy: 0.9555555555555556


In [14]:
gbr1 = GradientBoostingClassifier(n_estimators = 200, max_depth = 1, random_state = 42)

In [15]:
gbr1.fit(X_train,y_train)

GradientBoostingClassifier(max_depth=1, n_estimators=200, random_state=42)

GradientBoostingClassifier(max_depth=1, n_estimators=200, random_state=42)

In [16]:
pred_y = gbr1.predict(X_test)

In [17]:
accuracy_score(y_test,pred_y)

1.0

1.0

In [18]:
from  sklearn.ensemble import RandomForestClassifier
regressor = RandomForestClassifier(n_estimators=100,random_state=42)
regressor.fit(X_train,y_train)

y_preds = regressor.predict(X_test)

In [19]:
print('-----------------Gradient Boosting Classifier-------------')
print('accuracy_score:', accuracy_score(y_test,pred_y))
print('confusion_matrix:',confusion_matrix(y_test,pred_y))
print('classification_report:',classification_report(y_test,pred_y))
print('-----------------Random Forest-------------')
print('accuracy_score:',accuracy_score(y_test,y_preds))
print('confusion_matrix:',confusion_matrix(y_test,y_preds))
print('classification_report:',classification_report(y_test,y_preds))
print('-----------------Decision Tree Classifier-------------')
print('n\accuracy_score:',accuracy_score(y_test,y_pred1))
print('n\confusion_matrix:',confusion_matrix(y_test,y_pred1))
print('n\classification_report:',classification_report(y_test,y_pred1))

-----------------Gradient Boosting Classifier-------------
accuracy_score: 1.0
confusion_matrix: [[19  0  0]
 [ 0 13  0]
 [ 0  0 13]]
classification_report:               precision    recall  f1-score   support

           0       1.00      1.00      1.00        19
           1       1.00      1.00      1.00        13
           2       1.00      1.00      1.00        13

    accuracy                           1.00        45
   macro avg       1.00      1.00      1.00        45
weighted avg       1.00      1.00      1.00        45

-----------------Random Forest-------------
accuracy_score: 1.0
confusion_matrix: [[19  0  0]
 [ 0 13  0]
 [ 0  0 13]]
classification_report:               precision    recall  f1-score   support

           0       1.00      1.00      1.00        19
           1       1.00      1.00      1.00        13
           2       1.00      1.00      1.00        13

    accuracy                           1.00        45
   macro avg       1.00      1.00      1.00     

In [20]:
params = {
    
    'loss' : ['log_loss','deviance','exponential'],
    'learning_rate' : [0.001,0.1,0.5,0.7,0.9],
    'n_estimators' : [100,110,120] ,
    'subsample' : [0.1,0.2,0.3,0.6,0.9],
    'criterion' : ['friedman_mse','squared_error'],
    'max_features' :['auto','sqrt','log2','int','float'],
    'max_depth' : [100,110,120]
}

In [21]:
gbr = GradientBoostingClassifier(random_state = 42)
md = GridSearchCV(gbr,params,cv=5)
md.fit(X_train,y_train)

D:\Stats_software\Anaconda\lib\site-packages\sklearn\model_selection\_validation.py:372: FitFailedWarning: 
27000 fits failed out of a total of 33750.
The score on these train-test partitions for these parameters will be set to nan.
If these failures are not expected, you can try to debug them by setting error_score='raise'.

Below are more details about the failures:
--------------------------------------------------------------------------------
11250 fits failed with the following error:
Traceback (most recent call last):
  File "D:\Stats_software\Anaconda\lib\site-packages\sklearn\model_selection\_validation.py", line 680, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "D:\Stats_software\Anaconda\lib\site-packages\sklearn\ensemble\_gb.py", line 525, in fit
    self._check_params()
  File "D:\Stats_software\Anaconda\lib\site-packages\sklearn\ensemble\_gb.py", line 282, in _check_params
    raise ValueError("Loss '{0:s}' not supported. ".format(self.loss))

GridSearchCV(cv=5, estimator=GradientBoostingClassifier(random_state=42),
             param_grid={'criterion': ['friedman_mse', 'squared_error'],
                         'learning_rate': [0.001, 0.1, 0.5, 0.7, 0.9],
                         'loss': ['log_loss', 'deviance', 'exponential'],
                         'max_depth': [100, 110, 120],
                         'max_features': ['auto', 'sqrt', 'log2', 'int',
                                          'float'],
                         'n_estimators': [100, 110, 120],
                         'subsample': [0.1, 0.2, 0.3, 0.6, 0.9]})

GridSearchCV(cv=5, estimator=GradientBoostingClassifier(random_state=42),
             param_grid={'criterion': ['friedman_mse', 'squared_error'],
                         'learning_rate': [0.001, 0.1, 0.5, 0.7, 0.9],
                         'loss': ['log_loss', 'deviance', 'exponential'],
                         'max_depth': [100, 110, 120],
                         'max_features': ['auto', 'sqrt', 'log2', 'int',
                                          'float'],
                         'n_estimators': [100, 110, 120],
                         'subsample': [0.1, 0.2, 0.3, 0.6, 0.9]})

In [22]:
md.best_params_

{'criterion': 'friedman_mse',
 'learning_rate': 0.5,
 'loss': 'deviance',
 'max_depth': 100,
 'max_features': 'sqrt',
 'n_estimators': 100,
 'subsample': 0.6}

{'criterion': 'friedman_mse',
 'learning_rate': 0.5,
 'loss': 'deviance',
 'max_depth': 100,
 'max_features': 'sqrt',
 'n_estimators': 100,
 'subsample': 0.6}

In [23]:
md.best_score_

0.9523809523809523

0.9523809523809523