In [1]:
import pandas as pd
df = pd.read_csv(r'C:\Users\kelvin\Downloads\diabetes.csv')
df.head()

Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0            6      148             72             35        0  33.6   
1            1       85             66             29        0  26.6   
2            8      183             64              0        0  23.3   
3            1       89             66             23       94  28.1   
4            0      137             40             35      168  43.1   

   DiabetesPedigreeFunction  Age  Outcome  
0                     0.627   50        1  
1                     0.351   31        0  
2                     0.672   32        1  
3                     0.167   21        0  
4                     2.288   33        1

In [2]:
df.shape

(768, 9)

In [3]:
X = df.drop(columns = ['Outcome'])
X

Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0              6      148             72             35        0  33.6   
1              1       85             66             29        0  26.6   
2              8      183             64              0        0  23.3   
3              1       89             66             23       94  28.1   
4              0      137             40             35      168  43.1   
..           ...      ...            ...            ...      ...   ...   
763           10      101             76             48      180  32.9   
764            2      122             70             27        0  36.8   
765            5      121             72             23      112  26.2   
766            1      126             60              0        0  30.1   
767            1       93             70             31        0  30.4   

     DiabetesPedigreeFunction  Age  
0                       0.627   50  
1                       0.351   31  
2                       0.672   32  
3                       0.167   21  
4                       2.288   33  
..                        ...  ...  
763                     0.171   63  
764                     0.340   27  
765                     0.245   30  
766                     0.349   47  
767                     0.315   23  

[768 rows x 8 columns]

In [4]:
y = df['Outcome'].values
y[0:5]

array([1, 0, 1, 0, 1], dtype=int64)

In [5]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.2,random_state=42,stratify=y)

In [6]:
from sklearn.neighbors import KNeighborsClassifier
knn = KNeighborsClassifier(n_neighbors =3)
knn.fit(X_train,y_train)

knn.predict(X_test)[0:5]

array([1, 0, 0, 0, 0], dtype=int64)

In [7]:
knn.score(X_test,y_test)

0.6948051948051948

In [12]:
from sklearn.model_selection import cross_val_score
import numpy as np

knn_cv = KNeighborsClassifier(n_neighbors = 3)
cv_scores = cross_val_score(knn_cv,X,y,cv=10)
print('cv_scores mean:{}'.format(np.mean(cv_scores)))
cv_scores

cv_scores mean:0.7030587833219413


array([0.64935065, 0.71428571, 0.68831169, 0.66233766, 0.74025974,
       0.77922078, 0.71428571, 0.72727273, 0.67105263, 0.68421053])

In [9]:
from sklearn.model_selection import GridSearchCV
knn2 = KNeighborsClassifier()
param_grid = {
    
    'n_neighbors':np.arange(1,25)
    
}

knn_gscv= GridSearchCV(knn2,param_grid,cv=5)
knn_gscv.fit(X,y)

GridSearchCV(cv=5, estimator=KNeighborsClassifier(),
             param_grid={'n_neighbors': array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24])})

In [10]:
knn_gscv.best_params_

{'n_neighbors': 14}

In [11]:
knn_gscv.best_score_

0.7578558696205755