In [1]:
 from sklearn.preprocessing import MaxAbsScaler

In [2]:
# There is parenthesis
from sklearn import preprocessing
scaler = preprocessing.StandardScaler()

In [3]:
#No parenthesis in standardscale & Case upperLower

from sklearn.preprocessing import StandardScaler

In [4]:
import numpy as np

X_train = np.array([
                   [1,-1,2],
                   [2,0,0],
                   [0,1,0]
        ]
)
X_train

array([[ 1, -1,  2],
       [ 2,  0,  0],
       [ 0,  1,  0]])

In [5]:
scaler = preprocessing.StandardScaler().fit(X_train)
scaler

StandardScaler()

In [6]:
scaler.mean_

array([1.        , 0.        , 0.66666667])

In [7]:
scaler.scale_

array([0.81649658, 0.81649658, 0.94280904])

In [8]:
X_scaled = scaler.transform(X_train)
X_scaled

array([[ 0.        , -1.22474487,  1.41421356],
       [ 1.22474487,  0.        , -0.70710678],
       [-1.22474487,  1.22474487, -0.70710678]])

In [9]:
X_scaled.mean(axis=0)

array([0.00000000e+00, 0.00000000e+00, 7.40148683e-17])

In [10]:
X_scaled.std(axis=0)

array([1., 1., 1.])

In [11]:
train = np.array([
                     [5,2,0],
                     [2,5,2],
                     [3,1,7 ],
                     [4,7,4 ]
         
                ])
train

array([[5, 2, 0],
       [2, 5, 2],
       [3, 1, 7],
       [4, 7, 4]])

In [12]:
sc_tr = scaler.transform(train)
sc_tr

array([[ 4.89897949,  2.44948974, -0.70710678],
       [ 1.22474487,  6.12372436,  1.41421356],
       [ 2.44948974,  1.22474487,  6.71751442],
       [ 3.67423461,  8.5732141 ,  3.53553391]])

In [13]:
sc_tr.mean(axis=0)

array([3.06186218, 4.59279327, 2.74003878])

In [14]:
sc_tr.std(axis=0)

array([1.36930639, 2.92083036, 2.74288853])

In [15]:
X_train

array([[ 1, -1,  2],
       [ 2,  0,  0],
       [ 0,  1,  0]])

In [16]:
min_max_scaler = preprocessing.MinMaxScaler()
X_train_mimmax = min_max_scaler.fit_transform(X_train)
X_train_mimmax

array([[0.5, 0. , 1. ],
       [1. , 0.5, 0. ],
       [0. , 1. , 0. ]])

In [17]:
X_test = np.array([[-3,-1,4]])
X_test_minmax = min_max_scaler.transform(X_test)
X_test_minmax

array([[-1.5,  0. ,  2. ]])

In [18]:
min_max_scaler.scale_

array([0.5, 0.5, 0.5])

In [19]:
min_max_scaler.min_

array([0. , 0.5, 0. ])

In [20]:
X_train

array([[ 1, -1,  2],
       [ 2,  0,  0],
       [ 0,  1,  0]])

In [21]:
from sklearn.datasets import load_iris
X,y = load_iris(return_X_y=True)

In [22]:
print(X)


[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]
 [5.4 3.9 1.7 0.4]
 [4.6 3.4 1.4 0.3]
 [5.  3.4 1.5 0.2]
 [4.4 2.9 1.4 0.2]
 [4.9 3.1 1.5 0.1]
 [5.4 3.7 1.5 0.2]
 [4.8 3.4 1.6 0.2]
 [4.8 3.  1.4 0.1]
 [4.3 3.  1.1 0.1]
 [5.8 4.  1.2 0.2]
 [5.7 4.4 1.5 0.4]
 [5.4 3.9 1.3 0.4]
 [5.1 3.5 1.4 0.3]
 [5.7 3.8 1.7 0.3]
 [5.1 3.8 1.5 0.3]
 [5.4 3.4 1.7 0.2]
 [5.1 3.7 1.5 0.4]
 [4.6 3.6 1.  0.2]
 [5.1 3.3 1.7 0.5]
 [4.8 3.4 1.9 0.2]
 [5.  3.  1.6 0.2]
 [5.  3.4 1.6 0.4]
 [5.2 3.5 1.5 0.2]
 [5.2 3.4 1.4 0.2]
 [4.7 3.2 1.6 0.2]
 [4.8 3.1 1.6 0.2]
 [5.4 3.4 1.5 0.4]
 [5.2 4.1 1.5 0.1]
 [5.5 4.2 1.4 0.2]
 [4.9 3.1 1.5 0.2]
 [5.  3.2 1.2 0.2]
 [5.5 3.5 1.3 0.2]
 [4.9 3.6 1.4 0.1]
 [4.4 3.  1.3 0.2]
 [5.1 3.4 1.5 0.2]
 [5.  3.5 1.3 0.3]
 [4.5 2.3 1.3 0.3]
 [4.4 3.2 1.3 0.2]
 [5.  3.5 1.6 0.6]
 [5.1 3.8 1.9 0.4]
 [4.8 3.  1.4 0.3]
 [5.1 3.8 1.6 0.2]
 [4.6 3.2 1.4 0.2]
 [5.3 3.7 1.5 0.2]
 [5.  3.3 1.4 0.2]
 [7.  3.2 4.7 1.4]
 [6.4 3.2 4.5 1.5]
 [6.9 3.1 4.

In [23]:
print(y)

[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2]


In [24]:
enc = preprocessing.OrdinalEncoder()
X = [['Male','from US','uses Safari','female','from European','uses forma']]
enc.fit(X)

OrdinalEncoder()

In [25]:
enc.transform([['Male','from US','uses Safari','female','from European','uses forma']])

array([[0., 0., 0., 0., 0., 0.]])

In [26]:
# enc = preprocessing.OrdinalEncoder(encoded_missing_value = -1)
# X = [['male'],['female'],[np.nan],['female']]
# enc.fit_transform(X)

In [27]:
from sklearn.pipeline import Pipeline
from sklearn.impute import SimpleImputer
enc = Pipeline(steps = [
                     ("encoder" ,preprocessing.OrdinalEncoder()),
                     ('imputer',SimpleImputer(strategy ="constant",fill_value=-1)),
                      ])
enc.fit_transform(X)


array([[0., 0., 0., 0., 0., 0.]])

In [28]:
x = [['Kelvin'],['Jones'],[np.nan],['Houses'],['City']]
x1 =[[21],[np.nan],[3],[2],[7]]

In [29]:
import sklearn.preprocessing 
en = preprocessing.OrdinalEncoder()
ed_d = en.fit_transform(x)
ed_d

array([[ 3.],
       [ 2.],
       [nan],
       [ 1.],
       [ 0.]])

In [30]:
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import OrdinalEncoder
n1 = Pipeline( steps = [  ('scaler',StandardScaler()),
                          ('encoder',(OrdinalEncoder()))  , 
                          ('imputer',(SimpleImputer(strategy = "constant", fill_value=1)))
                      ]
            )
n1.fit_transform(x1)

array([[3.],
       [1.],
       [1.],
       [0.],
       [2.]])

In [31]:
n2 = preprocessing.OneHotEncoder()
x
n2.fit(x)
n2.transform([['Kelvin'],['Jones'],[np.nan],['Houses'],['City']]).toarray()

array([[0., 0., 0., 1., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1.],
       [0., 1., 0., 0., 0.],
       [1., 0., 0., 0., 0.]])

In [32]:
n2.categories_

[array(['City', 'Houses', 'Jones', 'Kelvin', nan], dtype=object)]

In [33]:
#explicitly specify  using parameter categories
genders = ['female','male']
locations = ['from Africa', 'from  Asia','from Europe','from US']
browsers = ['uses chrome','Uses Firefox','uses IE','Uses Safari']
n3 = preprocessing.OneHotEncoder(categories =[genders,locations,browsers])
X = [['male','from US','Uses Safari'],['female','from Europe','Uses Safari']]
n3.fit(X)


a =n3.transform([['female','from  Asia','uses chrome']]).toarray()

In [34]:
X = [['male','from US','Uses Safari'],['female','from Europe','Uses Safari']]

In [35]:
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import OrdinalEncoder
from sklearn.preprocessing import OneHotEncoder

n1 = Pipeline( steps = [  ('scaler',StandardScaler()),
                          ('encoder',(OneHotEncoder()))  , 
                          ('imputer',(SimpleImputer(strategy = "constant", fill_value=1)))
                      ]
            )
b = n1.fit_transform(x1).toarray()

In [36]:
a

array([[1., 0., 0., 1., 0., 0., 1., 0., 0., 0.]])

In [37]:
b

array([[0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.],
       [0., 1., 0., 0., 0.],
       [1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0.]])

In [44]:
sns.get_dataset_names()

['anagrams',
 'anscombe',
 'attention',
 'brain_networks',
 'car_crashes',
 'diamonds',
 'dots',
 'dowjones',
 'exercise',
 'flights',
 'fmri',
 'geyser',
 'glue',
 'healthexp',
 'iris',
 'mpg',
 'penguins',
 'planets',
 'seaice',
 'taxis',
 'tips',
 'titanic']

In [48]:
import seaborn as sns
data = sns.load_dataset('iris')
data

sepal_length  sepal_width  petal_length  petal_width    species
0             5.1          3.5           1.4          0.2     setosa
1             4.9          3.0           1.4          0.2     setosa
2             4.7          3.2           1.3          0.2     setosa
3             4.6          3.1           1.5          0.2     setosa
4             5.0          3.6           1.4          0.2     setosa
..            ...          ...           ...          ...        ...
145           6.7          3.0           5.2          2.3  virginica
146           6.3          2.5           5.0          1.9  virginica
147           6.5          3.0           5.2          2.0  virginica
148           6.2          3.4           5.4          2.3  virginica
149           5.9          3.0           5.1          1.8  virginica

[150 rows x 5 columns]

In [51]:
from sklearn.pipeline import Pipeline
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import OneHotEncoder,OrdinalEncoder,StandardScaler

In [101]:
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import OrdinalEncoder
from sklearn.preprocessing import OneHotEncoder

md = Pipeline( steps = [  
#                            ('scaler',StandardScaler()),
                          ('encoder',(OneHotEncoder())) ,
                          ('imputer',(SimpleImputer(strategy = "constant", fill_value=1)))
                      ]
            )
md.fit_transform(np.array(data['species'].values).reshape(1,-1)).toarray()

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1., 1., 1., 1., 1.]])