In [22]:
import pandas as pd
import warnings
warnings.simplefilter('ignore')

data =pd.read_csv(r'C:\Users\kelvin\Downloads\archive (36)\WineQT.csv')
data = data.values
data

array([[7.400e+00, 7.000e-01, 0.000e+00, ..., 9.400e+00, 5.000e+00,
        0.000e+00],
       [7.800e+00, 8.800e-01, 0.000e+00, ..., 9.800e+00, 5.000e+00,
        1.000e+00],
       [7.800e+00, 7.600e-01, 4.000e-02, ..., 9.800e+00, 5.000e+00,
        2.000e+00],
       ...,
       [6.200e+00, 6.000e-01, 8.000e-02, ..., 1.050e+01, 5.000e+00,
        1.594e+03],
       [5.900e+00, 5.500e-01, 1.000e-01, ..., 1.120e+01, 6.000e+00,
        1.595e+03],
       [5.900e+00, 6.450e-01, 1.200e-01, ..., 1.020e+01, 5.000e+00,
        1.597e+03]])

In [23]:
import numpy as np

In [24]:
data[data[:,-1]<5.5,-1]-0
data[data[:,-1]>=5.5,-1] = 1

In [25]:
data[:10]

array([[7.400e+00, 7.000e-01, 0.000e+00, 1.900e+00, 7.600e-02, 1.100e+01,
        3.400e+01, 9.978e-01, 3.510e+00, 5.600e-01, 9.400e+00, 5.000e+00,
        0.000e+00],
       [7.800e+00, 8.800e-01, 0.000e+00, 2.600e+00, 9.800e-02, 2.500e+01,
        6.700e+01, 9.968e-01, 3.200e+00, 6.800e-01, 9.800e+00, 5.000e+00,
        1.000e+00],
       [7.800e+00, 7.600e-01, 4.000e-02, 2.300e+00, 9.200e-02, 1.500e+01,
        5.400e+01, 9.970e-01, 3.260e+00, 6.500e-01, 9.800e+00, 5.000e+00,
        2.000e+00],
       [1.120e+01, 2.800e-01, 5.600e-01, 1.900e+00, 7.500e-02, 1.700e+01,
        6.000e+01, 9.980e-01, 3.160e+00, 5.800e-01, 9.800e+00, 6.000e+00,
        3.000e+00],
       [7.400e+00, 7.000e-01, 0.000e+00, 1.900e+00, 7.600e-02, 1.100e+01,
        3.400e+01, 9.978e-01, 3.510e+00, 5.600e-01, 9.400e+00, 5.000e+00,
        4.000e+00],
       [7.400e+00, 6.600e-01, 0.000e+00, 1.800e+00, 7.500e-02, 1.300e+01,
        4.000e+01, 9.978e-01, 3.510e+00, 5.600e-01, 9.400e+00, 5.000e+00,
        5.00

In [26]:
# np.set_printoptions({formatter=('float':'{:0.2f}'.format})

In [27]:
X = data[:,:-2]
X

array([[ 7.4  ,  0.7  ,  0.   , ...,  3.51 ,  0.56 ,  9.4  ],
       [ 7.8  ,  0.88 ,  0.   , ...,  3.2  ,  0.68 ,  9.8  ],
       [ 7.8  ,  0.76 ,  0.04 , ...,  3.26 ,  0.65 ,  9.8  ],
       ...,
       [ 6.2  ,  0.6  ,  0.08 , ...,  3.45 ,  0.58 , 10.5  ],
       [ 5.9  ,  0.55 ,  0.1  , ...,  3.52 ,  0.76 , 11.2  ],
       [ 5.9  ,  0.645,  0.12 , ...,  3.57 ,  0.71 , 10.2  ]])

In [28]:
Y = data[:,-1]
Y

array([0., 1., 2., ..., 1., 1., 1.])

In [29]:
print(X.shape,Y.shape)

(1143, 11) (1143,)


In [30]:
mean = X.mean(axis=0)
mean

array([ 8.31111111,  0.53133858,  0.26836395,  2.53215223,  0.08693263,
       15.61548556, 45.91469816,  0.99673041,  3.31101487,  0.65770779,
       10.4421114 ])

In [31]:
std = X.std(axis=0)
std

array([1.74683037e+00, 1.79554596e-01, 1.96599794e-01, 1.35532420e+00,
       4.72466566e-02, 1.02460011e+01, 3.27677868e+01, 1.92422483e-03,
       1.56595513e-01, 1.70324158e-01, 1.08172210e+00])

In [32]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense

In [33]:
model = Sequential()
model.add(Dense(8,input_dim=len(X[0,:]),activation = 'relu'))
model.add(Dense(4,activation = 'relu'))
model.add(Dense(1,activation = 'sigmoid'))

In [34]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(X,Y,test_size=0.3,random_state=42)
print(X_train.shape)
print(X_test.shape)
print(y_train.shape)
print(y_test.shape)

(800, 11)
(343, 11)
(800,)
(343,)


In [35]:
model.summary()

Model: "sequential_1"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense_3 (Dense)             (None, 8)                 96        
                                                                 
 dense_4 (Dense)             (None, 4)                 36        
                                                                 
 dense_5 (Dense)             (None, 1)                 5         
                                                                 
Total params: 137
Trainable params: 137
Non-trainable params: 0
_________________________________________________________________


In [36]:
model.compile(loss='binary_crossentropy',optimizer='rmsprop',metrics=['accuracy'])

In [37]:
model.fit(x=X_train,y=y_train,epochs=256,verbose=1)

Epoch 1/256
25/25 [==============================] - 1s 4ms/step - loss: 0.2241 - accuracy: 0.9812
Epoch 2/256
25/25 [==============================] - 0s 4ms/step - loss: 0.0325 - accuracy: 0.9962
Epoch 3/256
25/25 [==============================] - 0s 4ms/step - loss: -0.0221 - accuracy: 0.9962
Epoch 4/256
25/25 [==============================] - 0s 4ms/step - loss: -0.0404 - accuracy: 0.9962
Epoch 5/256
25/25 [==============================] - 0s 4ms/step - loss: -0.0503 - accuracy: 0.9962
Epoch 6/256
25/25 [==============================] - 0s 4ms/step - loss: -0.0579 - accuracy: 0.9962
Epoch 7/256
25/25 [==============================] - 0s 4ms/step - loss: -0.0640 - accuracy: 0.9962
Epoch 8/256
25/25 [==============================] - 0s 4ms/step - loss: -0.0699 - accuracy: 0.9962
Epoch 9/256
25/25 [==============================] - 0s 4ms/step - loss: -0.0761 - accuracy: 0.9962
Epoch 10/256
25/25 [==============================] - 0s 6ms/step - loss: -0.0833 - accuracy: 0.9962
E

25/25 [==============================] - 0s 3ms/step - loss: -1.1304 - accuracy: 0.9962
Epoch 83/256
25/25 [==============================] - 0s 3ms/step - loss: -1.1663 - accuracy: 0.9962
Epoch 84/256
25/25 [==============================] - 0s 3ms/step - loss: -1.1912 - accuracy: 0.9962
Epoch 85/256
25/25 [==============================] - 0s 3ms/step - loss: -1.2224 - accuracy: 0.9962
Epoch 86/256
25/25 [==============================] - 0s 3ms/step - loss: -1.2497 - accuracy: 0.9962
Epoch 87/256
25/25 [==============================] - 0s 3ms/step - loss: -1.2732 - accuracy: 0.9962
Epoch 88/256
25/25 [==============================] - 0s 3ms/step - loss: -1.2942 - accuracy: 0.9962
Epoch 89/256
25/25 [==============================] - 0s 3ms/step - loss: -1.3267 - accuracy: 0.9962
Epoch 90/256
25/25 [==============================] - 0s 3ms/step - loss: -1.3521 - accuracy: 0.9962
Epoch 91/256
25/25 [==============================] - 0s 3ms/step - loss: -1.3783 - accuracy: 0.9962
Epo

25/25 [==============================] - 0s 4ms/step - loss: -4.6382 - accuracy: 0.9962
Epoch 163/256
25/25 [==============================] - 0s 4ms/step - loss: -4.7003 - accuracy: 0.9962
Epoch 164/256
25/25 [==============================] - 0s 4ms/step - loss: -4.7609 - accuracy: 0.9962
Epoch 165/256
25/25 [==============================] - 0s 4ms/step - loss: -4.8179 - accuracy: 0.9962
Epoch 166/256
25/25 [==============================] - 0s 4ms/step - loss: -4.8869 - accuracy: 0.9962
Epoch 167/256
25/25 [==============================] - 0s 4ms/step - loss: -4.9686 - accuracy: 0.9962
Epoch 168/256
25/25 [==============================] - 0s 5ms/step - loss: -5.0469 - accuracy: 0.9962
Epoch 169/256
25/25 [==============================] - 0s 4ms/step - loss: -5.0794 - accuracy: 0.9962
Epoch 170/256
25/25 [==============================] - 0s 4ms/step - loss: -5.1651 - accuracy: 0.9962
Epoch 171/256
25/25 [==============================] - 0s 4ms/step - loss: -5.2492 - accuracy: 0

25/25 [==============================] - 0s 3ms/step - loss: -11.8174 - accuracy: 0.9962
Epoch 243/256
25/25 [==============================] - 0s 3ms/step - loss: -11.9133 - accuracy: 0.9962
Epoch 244/256
25/25 [==============================] - 0s 3ms/step - loss: -12.0315 - accuracy: 0.9962
Epoch 245/256
25/25 [==============================] - 0s 3ms/step - loss: -12.1364 - accuracy: 0.9962
Epoch 246/256
25/25 [==============================] - 0s 3ms/step - loss: -12.2627 - accuracy: 0.9962
Epoch 247/256
25/25 [==============================] - 0s 4ms/step - loss: -12.3684 - accuracy: 0.9962
Epoch 248/256
25/25 [==============================] - 0s 3ms/step - loss: -12.4933 - accuracy: 0.9962
Epoch 249/256
25/25 [==============================] - 0s 3ms/step - loss: -12.6126 - accuracy: 0.9962
Epoch 250/256
25/25 [==============================] - 0s 3ms/step - loss: -12.7288 - accuracy: 0.9962
Epoch 251/256
25/25 [==============================] - 0s 3ms/step - loss: -12.8653 - a

In [38]:
test_loss,test_accuracy = model.evaluate(X,Y)
print(test_loss,test_accuracy)

36/36 [==============================] - 0s 4ms/step - loss: -15.9412 - accuracy: 0.9956
-15.941218376159668 0.9956255555152893


In [39]:
y_pred=model.predict(X_test)
y_pred

11/11 [==============================] - 0s 3ms/step


array([[1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],

In [40]:
from sklearn.metrics import confusion_matrix,accuracy_score,classification_report
confusion_matrix(y_test,y_pred)

array([[341,   0,   0],
       [  1,   0,   0],
       [  1,   0,   0]], dtype=int64)

In [41]:
accuracy_score(y_test,y_pred)

0.9941690962099126

In [42]:
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

         1.0       0.99      1.00      1.00       341
         2.0       0.00      0.00      0.00         1
         3.0       0.00      0.00      0.00         1

    accuracy                           0.99       343
   macro avg       0.33      0.33      0.33       343
weighted avg       0.99      0.99      0.99       343

