$ \hat{Y} = \hat{\beta}_{0} + \sum \limits _{j=1}^ {n} X_{j}\hat{\beta}_{j} $

$  \hat{Y} = \hat{\beta}_{0}  + \hat{ \beta}_{ TV} * {TV} + \hat{ \beta}_{ radio} * {radio}+  \hat{ \beta}_{newspaper} * {newspaper}$



$ \hat{Y} = {({X}'X)}^{-1}{({X}'Y)} $

In [1]:
import pandas as pd
import numpy as np

import warnings
warnings.simplefilter("ignore")
np.set_printoptions(precision=3)

In [2]:
data =pd.read_csv("Advertising.csv")
data.head()

Unnamed: 0     TV  radio  newspaper  sales
0           1  230.1   37.8       69.2   22.1
1           2   44.5   39.3       45.1   10.4
2           3   17.2   45.9       69.3    9.3
3           4  151.5   41.3       58.5   18.5
4           5  180.8   10.8       58.4   12.9

In [3]:
inputt = data[["TV","radio","newspaper"]]
cons = pd.DataFrame(np.ones(len(data)),columns=['Constant'])

x = pd.concat([cons,inputt],axis=1)
y = data.sales.values

print(x.shape)
print(y.shape)

(200, 4)
(200,)


$ {({X}'X)}^{-1} $

${X} $

In [4]:
x= np.matrix(x)
x[:5]

matrix([[  1. , 230.1,  37.8,  69.2],
        [  1. ,  44.5,  39.3,  45.1],
        [  1. ,  17.2,  45.9,  69.3],
        [  1. , 151.5,  41.3,  58.5],
        [  1. , 180.8,  10.8,  58.4]])

$ {X}' $

In [5]:
xt = np.matrix.transpose(x)

$ {Y}_{i}$

In [6]:
y = np.matrix(data['sales'].values).transpose()
y[:5]

matrix([[22.1],
        [10.4],
        [ 9.3],
        [18.5],
        [12.9]])

$ {({X}'X)}$

In [7]:
xt_x = np.matmul(xt,x)
xt_x

matrix([[2.000e+02, 2.941e+04, 4.653e+03, 6.111e+03],
        [2.941e+04, 5.791e+06, 6.981e+05, 9.196e+05],
        [4.653e+03, 6.981e+05, 1.521e+05, 1.649e+05],
        [6.111e+03, 9.196e+05, 1.649e+05, 2.811e+05]])

$ {({X}'Y)}$

In [8]:
xt_y = np.matmul(xt,y)
xt_y

matrix([[  2804.5 ],
        [482108.34],
        [ 74126.39],
        [ 90851.03]])

$ \hat{Y} = {({X}'X)}^{-1}{({X}'Y)} $

In [9]:
betas = np.matmul(np.linalg.inv(xt_x),xt_y)
betas

matrix([[ 2.939e+00],
        [ 4.576e-02],
        [ 1.885e-01],
        [-1.037e-03]])

Intercept coeficients

$ \hat{\beta}_{0}$

In [10]:
intercept = betas[0]
intercept

matrix([[2.939]])

Slope Coefficients

$ \hat{\beta}_{TV}$ 

$ \hat{\beta}_{radio}$

$ \hat{\beta}_{newspaper}$

In [11]:
coefficients = betas[0:]
coefficients

matrix([[ 2.939e+00],
        [ 4.576e-02],
        [ 1.885e-01],
        [-1.037e-03]])

$  \hat{Y} = \hat{\beta}_{0}  + \hat{ \beta}_{ TV} * {TV} + \hat{ \beta}_{ radio} * {radio}+  \hat{ \beta}_{newspaper} * {newspaper}$

$\hat{Y} ={2.9272}  + {0.04576} * { TV} + { 0.1885} *{radio} - {0.001037} * {newspaper}$



Standard Errors

Step 1

$ \hat{Y} $

In [12]:
yhat = x.dot(betas)
yhat

matrix([[20.524],
        [12.338],
        [12.308],
        [17.598],
        [13.189],
        [12.478],
        [11.73 ],
        [12.123],
        [ 3.727],
        [12.551],
        [ 7.032],
        [17.285],
        [10.577],
        [ 8.826],
        [18.434],
        [20.819],
        [12.824],
        [23.225],
        [ 9.952],
        [14.166],
        [18.101],
        [14.741],
        [ 6.489],
        [16.546],
        [ 8.147],
        [15.61 ],
        [14.99 ],
        [17.052],
        [19.411],
        [ 9.144],
        [21.634],
        [11.346],
        [ 7.639],
        [18.864],
        [ 7.575],
        [17.007],
        [23.406],
        [15.623],
        [ 9.909],
        [20.448],
        [16.378],
        [17.296],
        [21.596],
        [13.964],
        [ 8.888],
        [15.162],
        [ 8.873],
        [21.723],
        [16.264],
        [ 8.168],
        [12.631],
        [ 9.34 ],
        [20.663],
        [19.945],
        [20.374],
        [2

Step 2 Sum Square of Error(SSE)

Simple Linear Regression

$SSE = {\sum\limits}_{i=1}^{n}{({Y}_{i} - \hat{Y})^2} $

Multple Linear Regression

$ {SSE} = {({Y}'Y)}^{-1}{(\hat{\beta}{X}{'Y})} $

Step 3
$$ 
SE = SSE / {(n-p)} 
$$

<!-- $$
  \int_0^\infty \frac{x^3}{e^x-1}\,dx = \frac{\pi^4}{15}
$$ -->

${({Y}'Y)}$

In [13]:
yt = np.transpose(y)
yt_y =np.matmul(yt,y)
yt_y

matrix([[44743.25]])

In [14]:
# np.transpose(x)

${\hat{\beta}{X}{'Y}} $

In [15]:
a=np.matmul(np.transpose(betas),xt)
b=np.matmul(a,y)
SSE =yt_y-b
print(SSE)
SE=SSE/(len(x)-len(betas))
SE

[[556.825]]


matrix([[2.841]])

In [16]:
#Alternatively
k=(yhat-y)
kl=pd.DataFrame(np.array(k),columns=['Difference'])
(kl.Difference**2).sum()/(len(x)-len(betas))

2.8409452188887108

In [17]:
SSE

matrix([[556.825]])

$SSR = {\hat{\beta}{X}{'Y}} - ({\sum\limits}_{i=j}^{n}{Y}_{j})^2/n $

In [18]:
yvalues = np.sum(np.array(y))
ymean=(yvalues)**2/len(y)
ymean

SSR = b - ymean
SSR

matrix([[4860.323]])

n= Observations

p = k + 1

k = No. Regressors

1 = intercept

$SST= {({Y}'Y)} - ({\sum\limits}_{i=j}^{n}{Y}_{j})^2$

$SST= {SSE} + {SSR}$

In [19]:
#Alternatively
SST =yt_y - ymean
SST

matrix([[5417.149]])

In [20]:
SST = SSE + SSR
SST

matrix([[5417.149]])

In [21]:
ANOVA=pd.DataFrame({
    "Sources of Variation":["Regression","Residual","Total"],
    "Sum of Squares":[SSR,SSE,SST],
    "DF":[len(betas)-1,len(x)-len(betas),len(x)-1],
    "MS":[SSR/((len(betas)-1)),SSE/((len(x)-len(betas))),""],
     "F-Statistics":[(SSR/(len(betas)-1))/ (SSE/(len(x)-len(betas))),"",""]

})
# ANOVA.index = [["Regression","Residual","Total"]]
ANOVA

Sources of Variation      Sum of Squares   DF                  MS   
0           Regression  [[[[[4860.323]]]]]    3  [[[[[1620.108]]]]]  \
1             Residual   [[[[[556.825]]]]]  196     [[[[[2.841]]]]]   
2                Total  [[[[[5417.149]]]]]  199                       

        F-Statistics  
0  [[[[[570.271]]]]]  
1                     
2

In [22]:
R_Sq = SSR/SST
R_Sq[0]

matrix([[0.897]])

In [23]:
Adj_R_SQ = 1-((len(x)-1)/(len(x)-len(betas)))*(1-R_Sq)
Adj_R_SQ

matrix([[0.896]])

In [24]:
#T-Statistics

In [25]:
xtxinv=np.linalg.inv(xt_x)
xtxinv

matrix([[ 3.424e-02, -9.353e-05, -3.926e-04, -2.080e-04],
        [-9.353e-05,  6.849e-07, -1.574e-07, -1.150e-07],
        [-3.926e-04, -1.574e-07,  2.610e-05, -6.266e-06],
        [-2.080e-04, -1.150e-07, -6.266e-06,  1.213e-05]])

In [ ]:
import math
from scipy.stats import f

SE_intercept = math.sqrt(np.array(xtxinv)[0][0]*SE)
t_Intercept = np.array(betas)[0] / math.sqrt(np.array(xtxinv)[0][0]*SE)
print(SE_intercept)
print(t_Intercept )

In [27]:
SE_TV = math.sqrt(np.array(xtxinv)[1][1]*SE)
t_TV = np.array(betas)[1] / math.sqrt(np.array(xtxinv)[1][1]*SE)
print(SE_TV)
print(t_TV )

0.0013948968069749388
[32.809]


In [28]:
SE_radio = math.sqrt(np.array(xtxinv)[2][2]*SE)
t_radio = np.array(betas)[2] / math.sqrt(np.array(xtxinv)[2][2]*SE)
print(SE_radio)
print(t_radio)

0.008611233967301719
[21.893]


In [29]:
SE_newspaper = math.sqrt(np.array(xtxinv)[3][3]*SE)
t_newspaper = np.array(betas)[3] / math.sqrt(np.array(xtxinv)[3][3]*SE)
print(SE_radio)
print(t_radio)

0.008611233967301719
[21.893]
